name: Docker Run

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler-version: ["8", "9", "10"]
    container: marekmosna/arm32v7-toolchain:${{ matrix.compiler-version }}
    env:
      BINARY_DIR: build
    steps:
      - name: Compiler version
        run: arm-none-eabi-cpp --version

      - name: Checkout project
        uses: actions/checkout@v2

      - name: CMake configure project
        run: cmake -S . -B ${{ env.BINARY_DIR }}

      - name: Build project
        run: make --directory ${{ env.BINARY_DIR }}

      - name: Run tests on project
        run: make --directory ${{ env.BINARY_DIR }} test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report-v${{ matrix.compiler-version }}
          path: ${{ env.BINARY_DIR }}/Testing/Temporary/LastTest.log

  test:
    runs-on: ubuntu-latest
    needs: build
    container: marekmosna/arm32v7-runtime:latest
    steps:
      - name: CMake version
        run: cmake --version
