name: Docker Run

on:
  push:
    branches: [ main, docker-image ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler-version: ["8", "9"]
    container: mosnamarek/arm32-toolchain:${{ matrix.compiler-version }}
    env:
      BINARY_DIR: build
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: CMake configure project
        run: cmake -S . -B ${{BINARY_DIR}}

      - name: Build project
        run: make --directory ${{BINARY_DIR}}

      - name: Run tests on project
        run: make --directory ${{BINARY_DIR}} test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report-v${{ matrix.compiler-version }}
          path: ${{BINARY_DIR}}/Testing/Temporary/LastTest.log
