name: Docker Run

on:
  push:
    branches: [ main, docker-image ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compiler-v9:
    runs-on: ubuntu-latest
    container: mosnamarek/arm32-toolchain:9
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: CMake configure project
        run: cmake -S . -B build

      - name: Build project
        run: make --directory build

      - name: Run tests on project
        run: make --directory build test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: build/Testing/Temporary/LastTest.log
  
  compiler-v8:
    runs-on: ubuntu-latest
    container: mosnamarek/arm32-toolchain:8
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: CMake configure project
        run: cmake -S . -B build

      - name: Build project
        run: make --directory build

      - name: Run tests on project
        run: make --directory build test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: build/Testing/Temporary/LastTest.log
