name: Docker Run

on:
  push:
    branches: [ main, docker-image ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    working-directory: docker-work

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: mosnamarek/arm32-runtime
    
    steps:
      - name: Get compiler version
        run: docker run --rm mosnamarek/arm32-runtime g++ --version
